server:
  shutdown: graceful

spring:
  application:
    name: common-service
  jpa:
    open-in-view: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:19411}/api/v2/spans

springdoc:
  info:
    title: Common Service API
    description: Assistudy Common Service
    version: 1.0.0
  swagger-ui:
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
