apiVersion: 1

datasources:
  # Prometheus - 메트릭 수집
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: '15s'
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: zipkin

  # Zipkin - 분산 트레이싱
  - name: Zipkin
    uid: zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    editable: false

  # InfluxDB - k6 부하 테스트 결과
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    editable: false
