livekit:
  url: ${LIVEKIT_URL}
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_SECRET}

spring:
  cloud:
    inetutils:
      preferred-networks:
        - 10.20

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO
    com.assistudy: INFO
