livekit:
  url: ${LIVEKIT_URL:http://localhost:7880}
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_SECRET:secret}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:eureka@localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.assistudy: DEBUG
