server:
  port: 8761

spring:
  application:
    name: discovery-service
  profiles:
    active: ${ACTIVE_PROFILE}
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
      fail-fast: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
