spring:
  application:
    name: discovery-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8761
  shutdown: graceful

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    username: ${EUREKA_USERNAME:eureka}
    password: ${EUREKA_PASSWORD:eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
