spring:
  application:
    name: log-send-service
  profiles:
    active: ${ACTIVE_PROFILE}
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
