spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: log-send-service
    instance-id: log-send-service:8085
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    root: INFO
    com.assistudy: INFO
