spring:
  application:
    name: log-send-service

server:
  port: 8085
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:19411}/api/v2/spans

springdoc:
  swagger-ui:
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
