spring:
  application:
    name: apigateway-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "User Service"
        url: "/user-service/v3/api-docs"
      - name: "Common Service"
        url: "/common-service/v3/api-docs"
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
