jwt:
  public-key: ${JWT_PUBLIC_KEY}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    root: INFO
    com.assistudy: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.security: WARN
