cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3001}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:assistudy}

jwt:
  public-key: ${JWT_PUBLIC_KEY}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:eureka@localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.assistudy: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
